### ISSUE TITLE
BBR的时候内核更新失败

### ISSUE THREAD

**Issue by LuffYH** [flyzy2005/ss-fly#13]

**Comment by flyzy2005** [comment]
嗯，内核更新对一些系统目前有一点问题，等有时间了再更新

**Comment by fafactx** [comment]
跟新时候选择低版本就行。只要大于4.9就行

**Comment by augustVino** [comment]
> 跟新时候选择低版本就行。只要大于4.9就行

您好，这个具体是怎么操作呢？是在执行 ss-fly/ss-fly.sh -bbr 命令时新增什么参数吗？
