### ISSUE TITLE
Centos7 多用户只有第一个用户能用

### ISSUE THREAD

**Issue by ShannonZ** [flyzy2005/ss-fly#14]
按照issue#7设置了多用户端口和密码，https://github.com/flyzy2005/ss-fly/issues/7
但是始终只有第一个用户能正常上网

**Comment by flyzy2005** [comment]
配置iptables，因为脚本默认只开放一个端口

**Comment by ShannonZ** [comment]
iptable中并没有屏蔽任何端口，也没有显式允许第一个端口。

**Comment by flyzy2005** [comment]
脚本里应该是在iptables里放行了你的ss端口的，具体代码在[ss-fly.sh](https://github.com/flyzy2005/ss-fly/blob/master/ss-fly.sh)的355行左右。
