### ISSUE TITLE
现在建好后不过一天就挂掉

### ISSUE THREAD

**Issue by gentlelion99** [flyzy2005/ss-fly#22]
怀疑有后门

**Comment by VampireStefan** [comment]
一模一样   不一会就挂

**Comment by flyzy2005** [comment]
那是最近严打，脚本都是开源的，哪里来的后门？可以用这个过度：[搬瓦工Just My Socks](https://www.flyzy2005.cn/tech/just-my-socks-buy/)

**Comment by lwlizhe** [comment]
我的安装完，也就连上ss试下效果，放一天后也挂了……不过我也是下了个非官方的ss客户端…………可能也是客户端的问题…………
现在用搬瓦工自带的那个，虽然隐藏了入口，但是还是能用的嘛…………

**Comment by lwlizhe** [comment]
不过感觉可能还真不是埋了后门，应该别的问题

**Comment by devhliu** [comment]
现在是什么问题啊？我连vultra 不到2分钟就被挂掉了

**Comment by HUTOYP** [comment]
> 现在是什么问题啊？我连vultra 不到2分钟就被挂掉了

相同的问题，用的aws的虚拟主机，连上没一会儿就不行了，重启服务过一会儿又不行了
