### ISSUE TITLE
libsodium安装失败

### ISSUE THREAD

**Issue by nNnCoder** [flyzy2005/ss-fly#23]
[信息] 正在设置防火墙...
[信息] 防火墙设置成功。
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) no
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... none
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/root/libsodium-1.0.16':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
[错误] libsodium安装失败!

**Comment by flyzy2005** [comment]
脚本不支持新的 CentOS 8 系统，可以先更换成别的系统再运行脚本（CentOS6或CentOS7或者其他）。

**Comment by nNnCoder** [comment]
> 脚本不支持新的 CentOS 8 系统，可以先更换成别的系统再运行脚本（CentOS6或CentOS7或者其他）。

谢谢答复，我刚已经尝试过了，安装了对应的库后，最终也是会出错。
我已近把OS版本改低了，问题已解决。谢谢！！

**Comment by myt111** [comment]
不行啊，CentOS7不行

**Comment by myt111** [comment]
大哥能具体点吗
