### ISSUE TITLE
无法上网

### ISSUE THREAD

**Issue by CoderGFWu** [flyzy2005/ss-fly#5]
我按照这个教程搭建成功了, 但是还是无法上网

**Comment by flyzy2005** [comment]
如果脚本显示已经搭建成功的话，那服务器就没有问题了。（如果是阿里云，AWS那些还需要手动开放安全组）
之后就是本地的问题，一般是因为防火墙或者是其他代理冲突了。可以关闭防火墙，以及[使用SwitchOmega来管理代理](https://www.flyzy2005.com/tech/switchyomega-proxy-server/)。

**Comment by CoderGFWu** [comment]
AWS需要开放什么端口什么协议, 主要是手机上的ss客户端可以使用, 电脑上用不了

**Comment by flyzy2005** [comment]
那服务器就没问题，检查你本地的问题吧。是不是之前用过别的代理

**Comment by CoderGFWu** [comment]
是的, 之前用ShadowsocksX-NG-R8连过其他的服务器, 后面其他服务器都挂了, 我就自己搞了一个, 后面自己服务器搭建好发现用ShadowsocksX-NG-R8连接还是上不了网, 卸载重装也没用, 该怎么处理?

**Comment by roachsinai** [comment]
怪了，我手机，电脑都不可以。
